version: "3.9"

services:
  # server:
  #   image: httpd:latest
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - .:/usr/local/apache2/htdocs
  
  server:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/var/www/html
    