#+TITLE: Fuzzbunch
#+INCLUDE: "../header.org"
#+AUTHOR: David Johnson
#+SETUPFILE: "../org-html-themes/org/theme-readtheorg-local-1.setup"
#+INDEX: Fuzzbunch
#+INDEX: Security!Fuzzbunch
#+TAG: Fuzzbunch
#+TAG: Windows

Fuzzbunch is a framework like Metasploit however it was written for Windows XP and who wants to use that. This tutorial will cover how to get it up and running on a Debian based distro.

* Prerequisites

- Debian based distro

- Wine

- fuzzbunch-debian

* Step 1:
The first thing we need to do is install Wine and clone fuzzbunch-debian.

As always we begin with an update.

#+BEGIN_EXAMPLE
apt update
#+END_EXAMPLE

Install Wine and other Wine tools.

#+BEGIN_EXAMPLE
apt install wine winbind winetricks
#+END_EXAMPLE

Add x32 architecture, update, and install wine 23

#+BEGIN_EXAMPLE
dpkg --add-architecture i386 && apt-get update && apt-get install wine32
#+END_EXAMPLE

Add variable.

#+BEGIN_EXAMPLE
WINEPREFIX="$HOME/.wine"
#+END_EXAMPLE

Set Wine Architecture.

#+BEGIN_EXAMPLE
WINEARCH=win32 wine wineboot
#+END_EXAMPLE

Add Path to bashrc

#+BEGIN_EXAMPLE
echo "export WINEPREFIX=$HOME/.wine-fuzzbunch" >> ~/.bashrc
#+END_EXAMPLE

Change into the Wine directory.

#+BEGIN_EXAMPLE
cd $HOME/.wine-fuzzbunch/drive_c
#+END_EXAMPLE

Clone Fuzzbunch-Debian.

#+BEGIN_EXAMPLE
git clone https://github.com/mdiazcl/fuzzbunch-debian.git
#+END_EXAMPLE

Install Python26

#+BEGIN_EXAMPLE
winetricks python26
#+END_EXAMPLE

* Step 2:
With Wine and fuzzbunch-debian installed its time to fire it up.

Change directories into fuzzbunch-debian/windows where fb.py is located.

#+BEGIN_EXAMPLE
cd $HOME/.wine-fuzzbunch/drive_c/fuzzbunch-debian/windows
#+END_EXAMPLE

Open up a Windows command prompt.

#+BEGIN_EXAMPLE
wine cmd.exe
#+END_EXAMPLE

We need to add Python26 and fuzzbunch-debian to Windows path.

#+BEGIN_EXAMPLE
path C:\Python26;C:\fuzzbunch-debian\windows\fuzzbunch;C:\Windows; C:\Windows\system32;C:\Windows\system32\webm
#+END_EXAMPLE

Start up fuzzbunch.

#+BEGIN_EXAMPLE
python fb.py
#+END_EXAMPLE

To use Eternalblue and Douplepulsar.

#+BEGIN_EXAMPLE
use EternalBlue
#+END_EXAMPLE

#+BEGIN_EXAMPLE
use DoublePulsar
#+END_EXAMPLE

* References

https://www.youtube.com/watch?v=fWwXjXexlT8

https://github.com/mdiazcl/fuzzbunch-debian

https://www.exploit-db.com/exploits/41891/

https://www.youtube.com/watch?v=wDAkiXxm1gE

https://github.com/ElevenPaths/Eternalblue-Doublepulsar-Metasploit

https://www.youtube.com/watch?v=mJWMqLF00fM
